/**
 * The site.
 *
 * Every row is from [`.agents/website-architecture.md`](../../../../.agents/website-architecture.md)
 * — the page hierarchy, the **SEO Intent by Page** table for the keywords and intent, the
 * **Internal Linking Plan** for `linkedFrom`, and the build phases. Two things are added from
 * elsewhere and both are sourced: the schema types are `.agents/gtm-strategy.md` §4's list,
 * and the answer and data pages are `docs/seo/decision.md` §3B.
 *
 * ⚠ **Nothing is live.** `live: false` on every row is the truth as of 2026-09-16, and it is
 * why the site health reads as it does. It is not a fixture waiting to be filled in — the
 * rebuilt site is the gate everything else waits on.
 *
 * `linkedFrom` is the **plan**, not a crawl. The architecture says what will link to what and
 * sets the rule — *"no orphan pages. Every page receives minimum 2 inbound internal links"* —
 * so a page with fewer than two here is one the plan itself leaves orphaned, which is a
 * planning defect worth seeing before it is a crawl result.
 */

import type { SitePage } from './page-seo';

export const SITE_PAGES: readonly SitePage[] = [
  {
    path: '/',
    title: 'Homepage',
    kind: 'home',
    phase: 1,
    primaryKeyword: 'analytical AI for business',
    secondaryKeywords: ['AI business research tool', 'AI market research'],
    intent: 'Branded + category',
    schema: 'Organization · WebSite',
    linkedFrom: ['every page — header'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/pricing',
    title: 'Pricing and plans',
    kind: 'analysis',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Conversion',
    schema: null,
    linkedFrom: ['/', 'header', 'footer', 'every ICP page', '/analyses/*', '/vs/*', '/security'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/enterprise',
    title: 'Enterprise',
    kind: 'analysis',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Conversion',
    schema: null,
    linkedFrom: ['/pricing', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/about',
    title: 'Company and story',
    kind: 'trust',
    phase: 2,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Trust',
    schema: 'Organization',
    linkedFrom: ['footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Role pages · ICP self-selection from the homepage ──────────────────────
  {
    path: '/consulting',
    title: 'For consultants',
    kind: 'icp',
    phase: 1,
    primaryKeyword: 'AI for consultants',
    secondaryKeywords: ['market analysis tool consulting', 'desk analysis AI'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer', '/pricing'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/strategy',
    title: 'For strategy teams',
    kind: 'icp',
    phase: 1,
    primaryKeyword: 'AI for strategy teams',
    secondaryKeywords: ['business analysis VP strategy', 'strategic options paper AI'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer', '/pricing'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/investors',
    title: 'For investors',
    kind: 'icp',
    phase: 1,
    primaryKeyword: 'AI due diligence tool',
    secondaryKeywords: ['investment analysis AI PE VC', 'sector analysis AI'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer', '/pricing'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/agencies',
    title: 'For agencies',
    kind: 'icp',
    phase: 2,
    primaryKeyword: 'AI for marketing agencies',
    secondaryKeywords: ['pitch analysis tool AI', 'agency competitive analysis'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/startups',
    title: 'For startups',
    kind: 'icp',
    phase: 2,
    primaryKeyword: 'AI market sizing tool',
    secondaryKeywords: ['startup market analysis', 'TAM SAM SOM analysis AI'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/category-managers',
    title: 'For category managers',
    kind: 'icp',
    phase: 2,
    primaryKeyword: 'category intelligence tool',
    secondaryKeywords: ['retail market analysis AI', 'category review analysis'],
    intent: 'ICP awareness',
    schema: null,
    linkedFrom: ['/', 'header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Use cases · the job, never the category ────────────────────────────────
  {
    path: '/use-cases/market-research',
    title: 'Market research',
    kind: 'use_case',
    phase: 2,
    primaryKeyword: 'AI market research report',
    secondaryKeywords: ['automated market research', 'AI industry analysis'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer', '/consulting'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/use-cases/business-case',
    title: 'Business case',
    kind: 'use_case',
    phase: 2,
    primaryKeyword: 'AI business case generator',
    secondaryKeywords: ['business case template AI', 'business case report'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer', '/strategy'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/use-cases/due-diligence',
    title: 'Due diligence',
    kind: 'use_case',
    phase: 2,
    primaryKeyword: 'AI due diligence tool',
    secondaryKeywords: ['automated due diligence report', 'M&A research AI'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer', '/investors', '/security'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/use-cases/competitive-analysis',
    title: 'Competitive analysis',
    kind: 'use_case',
    phase: 2,
    primaryKeyword: 'AI competitive analysis',
    secondaryKeywords: ['competitive landscape report generator'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer', '/agencies'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/use-cases/investment-thesis',
    title: 'Investment thesis',
    kind: 'use_case',
    phase: 2,
    primaryKeyword: 'investment thesis AI',
    secondaryKeywords: ['sector analysis report AI', 'investment memo AI'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer', '/investors'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/use-cases/rfp-response',
    title: 'RFP response',
    kind: 'use_case',
    phase: 3,
    primaryKeyword: 'AI RFP response generator',
    secondaryKeywords: ['RFP research automation', 'proposal research AI'],
    intent: 'Job to be done',
    schema: null,
    linkedFrom: ['header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Analysis types · product education ─────────────────────────────────────
  {
    path: '/analyses/brief',
    title: 'Brief — $15',
    kind: 'analysis',
    phase: 2,
    primaryKeyword: 'quick market research report',
    secondaryKeywords: ['15 minute market analysis AI'],
    intent: 'Product education',
    schema: null,
    linkedFrom: ['header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/analyses/study',
    title: 'Study — $80',
    kind: 'analysis',
    phase: 2,
    primaryKeyword: 'AI 100 page business report',
    secondaryKeywords: ['in-depth market research report AI'],
    intent: 'Product education',
    schema: null,
    linkedFrom: ['header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/analyses/intelligence',
    title: 'Intelligence — $300',
    kind: 'analysis',
    phase: 3,
    primaryKeyword: 'enterprise business intelligence AI',
    secondaryKeywords: ['due diligence report AI 24 hours'],
    intent: 'Product education',
    schema: null,
    linkedFrom: ['header', 'footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Comparison · the highest-intent traffic on the site ────────────────────
  {
    path: '/vs/chatgpt',
    title: 'Caspr vs ChatGPT',
    kind: 'comparison',
    phase: 2,
    primaryKeyword: 'Caspr vs ChatGPT research',
    secondaryKeywords: ['ChatGPT for business analysis alternative'],
    intent: 'Comparison',
    schema: null,
    linkedFrom: ['/pricing'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/vs/perplexity',
    title: 'Caspr vs Perplexity',
    kind: 'comparison',
    phase: 2,
    primaryKeyword: 'Caspr vs Perplexity business',
    secondaryKeywords: ['Perplexity for market research alternative'],
    intent: 'Comparison',
    schema: null,
    linkedFrom: ['/pricing'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/vs/consulting-firms',
    title: 'Caspr vs consulting firms',
    kind: 'comparison',
    phase: 2,
    primaryKeyword: 'AI alternative to consulting firms',
    secondaryKeywords: ['McKinsey alternative AI', 'consulting research AI'],
    intent: 'Comparison',
    schema: null,
    linkedFrom: ['/consulting'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/vs/statista',
    title: 'Caspr vs Statista',
    kind: 'comparison',
    phase: 2,
    primaryKeyword: 'Caspr vs Statista',
    secondaryKeywords: ['Ibisworld alternative AI', 'market data AI'],
    intent: 'Comparison',
    schema: null,
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Samples · the conversion asset, and a paid-engine condition ────────────
  {
    path: '/samples',
    title: 'Sample reports',
    kind: 'sample',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Conversion',
    schema: null,
    linkedFrom: ['/', 'footer', '/vs/chatgpt', '/vs/perplexity'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Trust and legal ───────────────────────────────────────────────────────
  {
    path: '/security',
    title: 'Security',
    kind: 'trust',
    phase: 2,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Trust — a product page, not a legal document',
    schema: null,
    linkedFrom: ['footer', '/pricing', '/enterprise', 'every ICP page'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/privacy',
    title: 'Privacy',
    kind: 'legal',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Legal',
    schema: null,
    linkedFrom: ['footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/terms',
    title: 'Terms',
    kind: 'legal',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Legal',
    schema: null,
    linkedFrom: ['footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/gdpr',
    title: 'GDPR',
    kind: 'legal',
    phase: 2,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Legal',
    schema: null,
    linkedFrom: ['footer'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/blog',
    title: 'Blog index',
    kind: 'blog',
    phase: 1,
    primaryKeyword: null,
    secondaryKeywords: [],
    intent: 'Navigation',
    schema: 'Blog',
    linkedFrom: ['header', 'footer', 'every post'],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Search answers · two a week, and where every other surface links ──────
  {
    path: '/answers/how-much-does-market-research-cost',
    title: 'How much does market research cost',
    kind: 'answer',
    phase: 2,
    primaryKeyword: 'how much does market research cost',
    secondaryKeywords: ['market research pricing', 'market research cost'],
    intent: '$300 CPC, KD 4 — the cluster is winnable immediately',
    schema: 'FAQPage',
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/answers/can-i-use-ai-research-for-a-client',
    title: 'Can I use AI research in work I hand to a client',
    kind: 'answer',
    phase: 2,
    primaryKeyword: 'can I use AI research in work I hand to a client',
    secondaryKeywords: ['citing AI generated content'],
    intent: 'Conversion only — near-zero volume, and it does its work at the point of doubt',
    schema: 'FAQPage',
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/alternatives/pitchbook-statista',
    title: 'PitchBook and Statista alternatives',
    kind: 'answer',
    phase: 3,
    primaryKeyword: 'pitchbook alternatives',
    secondaryKeywords: ['statista alternatives'],
    intent: 'One page, not eight — G2 owns this SERP end to end',
    schema: null,
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },

  // ── Data pages · the first three are T4 ───────────────────────────────────
  {
    path: '/data/saas-revenue-multiples',
    title: 'SaaS revenue multiples by sector',
    kind: 'data',
    phase: 3,
    primaryKeyword: 'SaaS revenue multiples by sector',
    secondaryKeywords: [],
    intent: 'T4 test page 1 — 8.5× NTM against 3.3× TTM, unreconciled',
    schema: 'Dataset',
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/data/industrial-valves-saudi-arabia',
    title: 'Industrial valves market, Saudi Arabia',
    kind: 'data',
    phase: 3,
    primaryKeyword: 'industrial valves market Saudi Arabia',
    secondaryKeywords: [],
    intent: 'T4 test page 2 — a B2B niche in an emerging geography',
    schema: 'Dataset',
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
  {
    path: '/data/copper-production-by-country',
    title: 'Copper production by country',
    kind: 'data',
    phase: 3,
    primaryKeyword: 'copper production by country',
    secondaryKeywords: [],
    intent: 'T4 test page 3 — the hardest case, searched by analysts and students alike',
    schema: 'Dataset',
    linkedFrom: [],
    live: false,
    indexed: false,
    titleTag: null,
    metaDescription: null,
  },
];
